[options]
addons_path = /mnt/extra-addons
admin_passwd = $pbkdf2-sha512$600000$ESLEuDdm7D2nVColRIhxDg$penktowVOYeg8KQs1FXQuFZh9L9yu270wVKQDNYJzeB8KotPf1sWUrx9PXGXID2xkVAs1sannUQz/I1pvq.jHQ
db_host = db
db_port = 5432
db_user = odoo
db_password = odoo

dbfilter = ^Phase3$